export const ipcChannels = {
	projectsList: "projects:list",
	projectsAdd: "projects:add",
	projectsRemove: "projects:remove",
	projectsReorder: "projects:reorder",
	projectsChanged: "projects:changed",
	filesList: "files:list",
	filesOpen: "files:open",
	filesShowInFolder: "files:show-in-folder",
	filesReadContent: "files:read-content",
	filesWriteContent: "files:write-content",
	sessionsList: "sessions:list",
	sessionsRename: "sessions:rename",
	sessionsCopy: "sessions:copy",
	sessionsExportHtml: "sessions:export-html",
	sessionsDelete: "sessions:delete",
	codexSessionsScan: "codex-sessions:scan",
	codexSessionsImport: "codex-sessions:import",
	claudeSessionsScan: "claude-sessions:scan",
	claudeSessionsImport: "claude-sessions:import",
	settingsGet: "settings:get",
	settingsUpdate: "settings:update",
	settingsTestPiProxy: "settings:test-pi-proxy",
	settingsApplyWindow: "settings:apply-window",
	skillsList: "skills:list",
	skillsCreate: "skills:create",
	skillsToggle: "skills:toggle",
	skillsDelete: "skills:delete",
	skillsOpenFolder: "skills:open-folder",
	extensionsList: "extensions:list",
	extensionsUninstall: "extensions:uninstall",
	gitBranches: "git:branches",
	gitCheckout: "git:checkout",
	gitCreateBranch: "git:create-branch",
	gitOriginalContent: "git:original-content",
	gitChangedFiles: "git:changed-files",
	piCheck: "pi:check",
	piCheckCustom: "pi:check-custom",
	appInfo: "app:info",
	appCheckUpdate: "app:check-update",
	appFeedbackEnvironment: "app:feedback-environment",
	appOpenExternal: "app:open-external",
	appRestart: "app:restart",
	appWindowMinimize: "app:window-minimize",
	appWindowToggleMaximize: "app:window-toggle-maximize",
	appWindowToggleAlwaysOnTop: "app:window-toggle-always-on-top",
	appWindowClose: "app:window-close",
	agentsList: "agents:list",
	agentsCreate: "agents:create",
	agentsRename: "agents:rename",
	agentsStop: "agents:stop",
	agentsPrompt: "agents:prompt",
	agentsAbort: "agents:abort",
	agentsExportHtml: "agents:export-html",
	agentsForkMessages: "agents:fork-messages",
	agentsForkSession: "agents:fork-session",
	agentsCloneSession: "agents:clone-session",
	agentsSwitchSession: "agents:switch-session",
	agentsReload: "agents:reload",
	agentsRestart: "agents:restart",
	agentsCompact: "agents:compact",
	agentsRuntimeState: "agents:runtime-state",
	agentsCycleModel: "agents:cycle-model",
	agentsAvailableModels: "agents:available-models",
	agentsSetModel: "agents:set-model",
	agentsCycleThinking: "agents:cycle-thinking",
	agentsSetThinking: "agents:set-thinking",
	agentsState: "agents:state",
	agentsEvent: "agents:event",
	agentsMessage: "agents:message",
	agentsLog: "agents:log",

	/** 流式思考内容更新，agent 忙碌时实时推送当前思考文本 */
	agentsThinking: "agents:thinking",

	configGetModels: "config:get-models",
	configGetAuth: "config:get-auth",
	configGetSettings: "config:get-settings",
	configSaveModels: "config:save-models",
	configSaveAuth: "config:save-auth",
	configSaveSettings: "config:save-settings",
	configSaveRaw: "config:save-raw",
	configExport: "config:export",
	configImport: "config:import",
	/** 从 provider 的 baseUrl + apiKey 拉取可用模型列表 */
	configFetchModels: "config:fetch-models",
	/** 快速测试 provider 连接：发送一条最小请求验证 baseUrl/apiKey/模型 是否正常 */
	configTestProvider: "config:test-provider",

	/** 切换开发者控制台 */
	appToggleDevTools: "app:toggle-devtools",

	/** RPC 日志，用于调试 */
	agentsRpcLog: "agents:rpc-log",

	terminalList: "terminal:list",
	terminalEnsure: "terminal:ensure",
	terminalCreate: "terminal:create",
	terminalInput: "terminal:input",
	terminalResize: "terminal:resize",
	terminalClose: "terminal:close",
	terminalData: "terminal:data",
	terminalExit: "terminal:exit",

	// ===== 飞书桥接 =====
	feishuConnect: "feishu:connect",
	feishuDisconnect: "feishu:disconnect",
	feishuStatus: "feishu:status",
	feishuStatusRequest: "feishu:status-request",
	feishuBotsList: "feishu:bots-list",
	feishuBotAdd: "feishu:bot-add",
	feishuBotRemove: "feishu:bot-remove",
	feishuBotConfig: "feishu:bot-config",
	feishuTestConnection: "feishu:test-connection",
	feishuBindingsList: "feishu:bindings-list",
	feishuBindingRemove: "feishu:binding-remove",
	feishuBindingUpdate: "feishu:binding-update",
	feishuBindingsChanged: "feishu:bindings-changed",
	feishuMessages: "feishu:messages",
	feishuQrCode: "feishu:qr-code",
	feishuConnectByBot: "feishu:connect-by-bot",
	/** Pi 创建会话时触发飞书自动拉群 */
	feishuAutoGroup: "feishu:auto-group",
} as const;
